Battle_SetTurnInfo(BATTLE_TURN.TIME,800);

Battle_SetTurnInfo(BATTLE_TURN.BOARD_LEFT,70);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_RIGHT,70);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_UP,70);
Battle_SetTurnInfo(BATTLE_TURN.BOARD_DOWN,70);
