/// @desc this will return a string for the keyboard key that you feed into it
/// @param KeyValue
function scr_keytostring(argument0){
	
	switch argument0
	{
		case	65:		return "A"       
		case	66:		return "B"       
		case	67:		return "C"       
		case	68:		return "D"       
		case	69:		return "E"       
		case	70:		return "F"       
		case	71:		return "G"       
		case	72:		return "H"       
		case	73:		return "I"       
		case	74:		return "J"       
		case	75:		return "K"       
		case	76:		return "L"       
		case	77:		return "M"       
		case	78:		return "N"       
		case	79:		return "O"       
		case	80:		return "P"       
		case	81:		return "Q"       
		case	82:		return "R"       
		case	83:		return "S"       
		case	84:		return "T"       
		case	85:		return "U"       
		case	86:		return "V"       
		case	87:		return "W"       
		case	88:		return "X"       
		case	89:		return "Y"       
		case	90:		return "Z"       
		case	162:	return "` `"		 
		case	163:	return "` `"		 
		case	164:	return "```"       
		case	165:	return "``"       
		case	186:	return ";"
		case	222:	return "'"
		case	13:		return "`"
		case	220:	return	"\\"
		case	8:		return	"`"
		case	219:	return "["
		case	221:	return "]"
		case	188:	return ","
		case	190:	return "."
		case	191:	return "/"
		case	16:		return "`"
		case	9:		return "`"
		case	192:	return "`"
		case	48:		return "0"
		case	49:		return "1"
		case	50:		return "2"
		case	51:		return "3"
		case	52:		return "4"
		case	53:		return "5"
		case	54:		return "6"
		case	55:		return "7"
		case	56:		return "8"
		case	57:		return "9"
		
		case	96:		return "` 0"
		case	97:		return "` 1"
		case	98:		return "` 2"
		case	99:		return "` 3"
		case	100:	return "` 4"
		case	101:	return "` 5"
		case	102:	return "` 6"
		case	103:	return "` 7"
		case	104:	return "` 8"
		case	105:	return "` 9"
		case	111:	return "` /"
		case	106:	return "` *"
		case	107:	return "` +"
		case	110:	return "` ."
		case	109:	return "` -"
		
		case	112:	return "`"
		case	113:	return "`"
		case	114:	return "`"
		case	115:	return "`"
		case	116:	return "`"
		case	117:	return "`"
		case	118:	return "`"
		case	119:	return "`"
		case	120:	return "`"
		case	121:	return "`"
		case	122:	return "`"
		case	123:	return "`"
		case	145:	return "`"
		case	19:		return "`"
		case	20:		return "` `"
		case	189:	return "-"
		case	187:	return "="
		case	45:		return "`"
		case	36:		return "`"
		case	33:		return "` `"
		case	34:		return "` `"
		case	35:		return "`"
		case	46:		return "`"
		case	144:	return "`"
		case	38:		return "`"
		case	40:		return "`"
		case	37:		return "`"
		case	39:		return "`"
		case	91:		return "`"
		case	92:		return "`"
		case	32:		return "`"
		case	0:		return " "
		case	179:	return "`"
		case	173:	return "`"
		case	174:	return "`"
		case	175:	return "`"

		default:		return "`"
	}
}